version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.08-22.04

    steps:
      - run:
          name: Install base packages
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake git gcc
      - checkout
      - run:
          name: Install app dependencies
          command: |
            sudo apt-get install -y qtbase5-dev libqt5opengl5-dev libsuitesparse-dev libboost-dev libeigen3-dev flex bison re2c libboost-program-options-dev libgtest-dev
      - run:
          name: Prepare build directory
          command: |
            mkdir build
            cd build
            cmake ..
      - run:
          name: Build
          command: |
            cd build
            make -j2
      - save_cache:
          key: v1-repo-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build

  test:
    docker:
      - image: cimg/base:2023.08-22.04
    steps:
      - restore_cache:
          key: v1-repo-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      
      - run:
          name: Install packages
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake
      - run:
          name: test  libfemp
          command: |
            cd build
            cd libfemp
            ctest

workflows:
  version: 2
  unscheduled:
    jobs:
      - build