
HEADERS += \
        src/InputStates/ISStart.h++ \
        src/InputStates/ISLeftClick.h++ \
        src/InputStates/InputState.h++ \
        src/InputStates/Input.h++ \
        src/InputStates/ISRightClick.h++ \
        src/InputStates/ISLeftDrag.h++ \
        src/InputStates/ISRightDrag.h++ \
        src/boundaries/SphericalBoundary.h++ \
        src/boundaries/BoundaryStrategy.h++ \
        src/boundaries/CollisionDetection.h++ \
        src/SceneGraphComponents/Operations/SelectRayIntersectionOperation.h++ \
        src/SceneGraphComponents/Operations/SelectFrustumInclusionOperation.h++ \
        src/SceneGraphComponents/Operations/OperationsVisitor.h++ \
        src/SceneGraphComponents/Operations/ToggleSelectionOperation.h++ \
        src/SceneGraphComponents/Operations/ToggleRenderOperation.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/StressFieldRepresentationPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldRepresentationPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/OpaqueRepresentationPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/ElementRepresentationPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/ElementRepresentationFlyweightFactory.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/StressField/StressFieldRepresentation.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/StressField/StressFieldFactory.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/StressField/StressTensor.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress33GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/VonMisesGradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/NeutralGradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain13GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress23GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/ConstantGradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress12GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain23GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain33GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain12GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain11GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress22GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress11GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress13GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain22GradientFieldPolicy.h++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/GradientFieldFlyweightFactory.h++ \
        src/SceneGraphComponents/SGCElement.h++ \
        src/SceneGraphComponents/DisplacementsRepresentationPolicy/NoDisplacementsPolicy.h++ \
        src/SceneGraphComponents/DisplacementsRepresentationPolicy/DisplacementsPolicy.h++ \
        src/SceneGraphComponents/DisplacementsRepresentationPolicy/DisplacementsRepresentationPolicy.h++ \
        src/SceneGraphComponents/SGCPickRay.h++ \
        src/SceneGraphComponents/SceneGraphException.h++ \
        src/SceneGraphComponents/Elements/Prism6.h++ \
        src/SceneGraphComponents/Elements/Tetrahedron10.h++ \
        src/SceneGraphComponents/Elements/Hexahedron20.h++ \
        src/SceneGraphComponents/Elements/Tetrahedron4.h++ \
        src/SceneGraphComponents/Elements/Prism18.h++ \
        src/SceneGraphComponents/Elements/Prism15.h++ \
        src/SceneGraphComponents/Elements/Hexahedron27.h++ \
        src/SceneGraphComponents/Elements/Hexahedron8.h++ \
        src/SceneGraphComponents/SGCNode.h++ \
        src/SceneGraphComponents/SceneGraphComponent.h++ \
        src/SceneGraphComponents/SceneComponentFactory.h++ \
        src/SceneGraphComponents/SGCNodeRestrictions.h++ \
        src/SceneGraphComponents/hud/HudObject.h++ \
        src/SceneGraphComponents/hud/HudSelection.h++ \
        src/ViewportStates/VPStateDisplacements.h++ \
        src/ViewportStates/ViewportState.h++ \
        src/ViewportStates/VPStateGradients.h++ \
        src/ViewportStates/VPStateModel.h++ \
        src/ViewportStates/VPStateTensorFields.h++ \
        src/PostprocessingViewport.h++ \
        src/ModelViewport.h++ \
        src/SceneGraph.h++ \
        src/ViewportData.h++ \
        src/RenderGroup.h++ \
        src/TensorFieldViewport.h++ \
        src/Camera.h++ \
        src/BaseViewport.h++ \


SOURCES += \
        src/InputStates/ISRightClick.c++ \
        src/InputStates/ISLeftClick.c++ \
        src/InputStates/InputState.c++ \
        src/InputStates/ISStart.c++ \
        src/InputStates/ISRightDrag.c++ \
        src/InputStates/Input.c++ \
        src/InputStates/ISLeftDrag.c++ \
        src/boundaries/SphericalBoundary.c++ \
        src/boundaries/BoundaryStrategy.c++ \
        src/boundaries/CollisionDetection.c++ \
        src/ViewportData.c++ \
        src/SceneGraphComponents/Operations/ToggleSelectionOperation.c++ \
        src/SceneGraphComponents/Operations/SelectFrustumInclusionOperation.c++ \
        src/SceneGraphComponents/Operations/SelectRayIntersectionOperation.c++ \
        src/SceneGraphComponents/Operations/ToggleRenderOperation.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldRepresentationPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/StressFieldRepresentationPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/OpaqueRepresentationPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/ElementRepresentationFlyweightFactory.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/ElementRepresentationPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/StressField/StressFieldFactory.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/StressField/StressTensor.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/StressField/StressFieldRepresentation.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/NeutralGradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/VonMisesGradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress33GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress22GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/ConstantGradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain22GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress23GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress11GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain33GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain11GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress12GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Stress13GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain23GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain13GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/Strain12GradientFieldPolicy.c++ \
        src/SceneGraphComponents/ElementRepresentationPolicy/GradientFieldPolicy/GradientFieldFlyweightFactory.c++ \
        src/SceneGraphComponents/SceneComponentFactory.c++ \
        src/SceneGraphComponents/DisplacementsRepresentationPolicy/DisplacementsPolicy.c++ \
        src/SceneGraphComponents/DisplacementsRepresentationPolicy/NoDisplacementsPolicy.c++ \
        src/SceneGraphComponents/DisplacementsRepresentationPolicy/DisplacementsRepresentationPolicy.c++ \
        src/SceneGraphComponents/SGCPickRay.c++ \
        src/SceneGraphComponents/SceneGraphComponent.c++ \
        src/SceneGraphComponents/Elements/Hexahedron8.c++ \
        src/SceneGraphComponents/Elements/Tetrahedron10.c++ \
        src/SceneGraphComponents/Elements/Prism18.c++ \
        src/SceneGraphComponents/Elements/Hexahedron20.c++ \
        src/SceneGraphComponents/Elements/Prism6.c++ \
        src/SceneGraphComponents/Elements/Tetrahedron4.c++ \
        src/SceneGraphComponents/Elements/Prism15.c++ \
        src/SceneGraphComponents/Elements/Hexahedron27.c++ \
        src/SceneGraphComponents/SGCNode.c++ \
        src/SceneGraphComponents/SGCElement.c++ \
        src/SceneGraphComponents/SGCNodeRestrictions.c++ \
        src/SceneGraphComponents/hud/HudSelection.c++ \
        src/ViewportStates/ViewportState.c++ \
        src/ViewportStates/VPStateModel.c++ \
        src/ViewportStates/VPStateDisplacements.c++ \
        src/ViewportStates/VPStateGradients.c++ \
        src/ViewportStates/VPStateTensorFields.c++ \
        src/TensorFieldViewport.c++ \
        src/RenderGroup.c++ \
        src/ModelViewport.c++ \
        src/SceneGraph.c++ \
        src/PostprocessingViewport.c++ \
        src/BaseViewport.c++ \
        src/Camera.c++ \
        src/SceneGraphComponents/Operations/OperationsVisitor.c++ \
        src/SceneGraphComponents/hud/HudObject.c++
